import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import { FilterProvider } from "@/context/FilterContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com"  />
        <link
          href="https://fonts.googleapis.com/css2?family=Rajdhani:wght@300;400;500;600;700&display=swap"
          rel="stylesheet"
        />
        
      </head>
      <body className={inter.className}><FilterProvider>
          {children}
        </FilterProvider></body>
      <Script src="https://www.gstatic.com/firebasejs/8.6.8/firebase-app.js"></Script>
      <Script src="https://www.gstatic.com/firebasejs/8.6.8/firebase-auth.js"></Script>
      
    </html>
  );
}
